#!/usr/bin/env python

import argparse
import json
import logging
import os
from pprint import pprint
from ansibullbot.utils.webscraper import GithubWebScraper


def main():

    parser = argparse.ArgumentParser()
    parser.add_argument("url")
    args = parser.parse_args()

    gws = GithubWebScraper()
    summaries = gws.get_issue_summaries(args.url, baseurl=args.url)
    print(json.dumps(sorted([int(x) for x in summaries.keys()])))


if __name__ == "__main__":
    main()
