- name: Stop prod bot
  hosts: ansibullbot.eng.ansible.com
  become: yes

  tasks:
    - name: PROD | Stop ansibullbot service
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - ansibullbot
        - ansibullbot-receiver

- name: Start dev bot
  hosts: ansibullbot-dev
  become: yes

  tasks:
    - name: DEV | Start ansibullbot services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - ansibullbot-receiver
        - ansibullbot
