- name: Stop dev bot
  hosts: ansibullbot-dev
  become: yes

  tasks:
    - name: DEV | Stop ansibullbot services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - ansibullbot
        - ansibullbot-receiver

- name: Start prod bot
  hosts: ansibullbot.eng.ansible.com
  become: yes

  tasks:
    - name: PROD | Start ansibullbot services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - ansibullbot-receiver
        - ansibullbot
