- name: Install ansibullbot
  hosts: ansibullbot.eng.ansible.com
  become: yes

  roles:
    - repo_epel
    - yum_cron
    - firewall
    - fail2ban
    - docker
    - mongodb
    - caddy
    - ansibullbot
